<a href="https://colab.research.google.com/github/ronaspen/deep-learning-challenge/blob/main/AlphabetSoupCharity_Optimisation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [22]:
# Drop the non-beneficial ID columns, 'EIN'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns = ['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [23]:
app_type_count = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = list(app_type_count.iloc[8:].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [24]:
cl_count = application_df['CLASSIFICATION'].value_counts()
cl_cleaned = cl_count.loc[cl_count > 1]

In [25]:
classifications_to_replace = list(cl_count.iloc[5:].index)
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
#The above is what I did in the first model, creating 'other' categories for the lower value counts of 'CLASSIFICATION' and 'APPLICATION TYPE'

In [27]:
# Look at NAME value counts for binning
name_counts = application_df['NAME'].value_counts()
name_counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [28]:
# Choose a cutoff value and create a list of names to be replaced
names_to_replace = list(name_counts[name_counts < 100].index)

# Replace in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(
        name, "Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                 25987
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
HONOR SOCIETY OF PHI KAPPA PHI                                          107
MONTANA 4-H FOUNDATION INC                                              107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
Name: NAME, dtype: int64

In [29]:
list_categorical = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
list_categorical

['NAME',
 'APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [30]:
dummies_df = pd.get_dummies(application_df)
dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CIVITAN INTERNATIONAL,NAME_DEMOLAY INTERNATIONAL,NAME_FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA,NAME_HABITAT FOR HUMANITY INTERNATIONAL INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [31]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = dummies_df['IS_SUCCESSFUL'].values
X = dummies_df.drop(columns='IS_SUCCESSFUL').values
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [32]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [33]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 10
hidden_layer2 = 8
hidden_layer3= 6


nn_2 = tf.keras.models.Sequential()

# First hidden layer
nn_2.add(tf.keras.layers.Dense(units=hidden_layer1,
             input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn_2.add(tf.keras.layers.Dense(
    units=hidden_layer2, activation="sigmoid"))

# Third hidden layer
nn_2.add(tf.keras.layers.Dense(
    units=hidden_layer3, activation="sigmoid"))

# Output layer
nn_2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_2.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_8 (Dense)             (None, 10)                750

 dense_9 (Dense)             (None, 8)                 88

 dense_10 (Dense)            (None, 6)                 54

 dense_11 (Dense)            (None, 1)                 7

=================================================================
Total params: 899 (3.51 KB)
Trainable params: 899 (3.51 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [34]:
# Compile the model
nn_2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [35]:
# Train the model
fit_model2 = nn_2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 3ms/step - loss: 0.6025 - accuracy: 0.6862
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5227 - accuracy: 0.7462
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5094 - accuracy: 0.7517
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5045 - accuracy: 0.7537
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5008 - accuracy: 0.7545
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4986 - accuracy: 0.7543
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4965 - accuracy: 0.7549
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4952 - accuracy: 0.7554
Epoch 9/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4940 - accuracy: 0.7566
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4937 - accuracy: 0.7572
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4932 - accuracy: 0.7579
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4923 - accuracy: 0.7579
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4915 - accuracy: 0.7591
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4914 - accuracy: 0.7581
Epoch 15/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4907 - accuracy: 0.7580
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4901 - accuracy: 0.7583
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4897 - accuracy: 0.7587
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4890 - accuracy: 0.7587
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4892 - accuracy: 0.7587
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4885 - accuracy: 0.7592
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4884 - accuracy: 0.7582
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4882 - accuracy: 0.7597
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4879 - accuracy: 0.7597
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4875 - accuracy: 0.7589
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4874 - accuracy: 0.7598
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4870 - accuracy: 0.7591
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4867 - accuracy: 0.7602
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4866 - accuracy: 0.7604
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4864 - accuracy: 0.7599
Epoch 30/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4862 - accuracy: 0.7597
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4858 - accuracy: 0.7605
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7599
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4855 - accuracy: 0.7600
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4855 - accuracy: 0.7594
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4851 - accuracy: 0.7599
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4855 - accuracy: 0.7593
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4851 - accuracy: 0.7593
Epoch 38/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4853 - accuracy: 0.7623
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4846 - accuracy: 0.7618
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4845 - accuracy: 0.7619
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4846 - accuracy: 0.7590
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4845 - accuracy: 0.7601
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4842 - accuracy: 0.7607
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4843 - accuracy: 0.7601
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4839 - accuracy: 0.7601
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4837 - accuracy: 0.7615
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4838 - accuracy: 0.7610
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4837 - accuracy: 0.7600
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4836 - accuracy: 0.7609
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4835 - accuracy: 0.7614

In [36]:
model_loss, model_accuracy = nn_2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4909 - accuracy: 0.7590 - 504ms/epoch - 2ms/step
Loss: 0.4908962845802307, Accuracy: 0.758950412273407

In [39]:
# Export our model to HDF5 file

filepath = r"C:\Users\rohan\OneDrive\Desktop\deep-learning-challenge\deep learning challenge\AlphabetSoupCharity_Optimization.h5"

nn_2.save(filepath, save_format='h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(